language: python
python:
  - "2.7"
install:
  - pip install --upgrade pytest
  - nvm install node
  - npm install -g npm@latest
  - npm install -g eslint eslint-plugin-inferno
  - pip install -r requirements-dev.txt
script:
  - npm run test
after_success:
  coveralls
