application: saylua-1280
version: 1
runtime: php55
api_version: 1
threadsafe: yes

skip_files:
- /?node_modules/*.*
- /?static/source/*.*

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static
  application_readable: true 

- url: /(.+\.php)$
  script: \1

- url: .*
  script: main.php
