# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

# Handlers define how to route requests to your application.
handlers:

# App Engine serves and caches static files contained in the listed directories
# (and subdirectories). Uncomment and set the directory as needed.
#- url: /client
#  static_dir: client

# For the interactive console
- url: /google_admin/.*
  script: google.appengine.ext.admin.application
  login: admin

# This handler is for Lets Encrypt challenges
- url: /\.well\-known\/acme\-challenge\/.*
  script: letsencrypt.app

# This handler tells app engine how to route requests to a WSGI application.
# The script value is in the format <path.to.module>.<wsgi_application>
# where <wsgi_application> is a WSGI application object.
- url: .*  # This regex directs all routes to main.app
  script: main.app
  secure: always

# Third party libraries that are included in the App Engine SDK must be listed
# here if you want to use them.  See
# https://developers.google.com/appengine/docs/python/tools/libraries27 for
# a list of libraries included in the SDK.  Third party libs that are *not* part
# of the App Engine SDK don't need to be listed here, instead add them to your
# project directory, either as a git submodule or as a plain subdirectory.
# TODO: List any other App Engine SDK libs you may need here.
libraries:
- name: PIL
  version: 1.1.7
- name: pycrypto
  version: latest
- name: MySQLdb
  version: latest
- name: ssl
  version: latest

# Files to ignore in production
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^saylua/static/source/.*
- ^node_modules/.*
- ^lib/PIL*

beta_settings:
    cloud_sql_instances: saylua-1280:us-central1:main-db
